### PR TITLE
Eigen upgrade

### PR DESCRIPTION
**Pull request by TSC21**
Here's the upgrade with the commit history.

**Compiled and approved.**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
This looks good, but why is there a merge conflict?

**Comment by TSC21** [comment]
Well probably those are the merging conflicts I was getting that I then solved manually. But then that's why I lost the commit history.

**Comment by LorenzMeier** [comment]
@TSC21 How about we pull in your branch just as "some version"? We don't actually need to merge.

**Comment by LorenzMeier** [comment]
Which Eigen release is this?

**Comment by TSC21** [comment]
I'm not being able to push the bitbucket repo directly into `/src/lib/eigen` in order to correct the merging conflicts and at the same time keep the commit history. Isn't it easier to create a new branch with the code from https://github.com/TSC21/eigen/tree/eigen_upgrade?

**Comment by TSC21** [comment]
> @TSC21 How about we pull in your branch just as "some version"? We don't actually need to merge.

Ups I just read this now after refreshing the page. Well I think it's latest **3.2.5** with some more commits: https://bitbucket.org/eigen/eigen/src. So yes it seems a good idea. Also may you close https://github.com/PX4/Firmware/pull/2681 and add the has of the the new version?

**Comment by LorenzMeier** [comment]
All done and in PX4/Firmware master.

**Comment by TSC21** [comment]
Ok great

**Pull request closed without merging**
